[
  {
    "fullname": "Amanda Gboyega Babatunde",
    "email": "amandababatunde@hotmail.com",
    "username": "amandababatunde68",
    "phoneNumber": "07069416777",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "11 1 08",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": "chinyerebabatunde",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Eketi Folake Ayantola",
    "email": "eketiayantola@gmail.com",
    "username": "eketiayantola53",
    "phoneNumber": "09069516811",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "4 7 07",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": "wasiuayantola",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Esther Eketi Monday",
    "email": "esthermonday@hotmail.com",
    "username": "esthermonday5",
    "phoneNumber": "08169616845",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "8 18 06",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": "iniobongmonday",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Iniobong Aisha Okeke",
    "email": "iniobongokeke@aol.com",
    "username": "iniobongokeke1",
    "phoneNumber": "09069716879",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "3 28 03",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": "ibukunokeke",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amara Chikaodili Atanda",
    "email": "amaraatanda@outlook.com",
    "username": "amaraatanda14",
    "phoneNumber": "07069816913",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "5 8 06",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": "musaatanda",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Ngozi Chikaodili Obiwuru",
    "email": "ngoziobiwuru@gmail.com",
    "username": "ngoziobiwuru77",
    "phoneNumber": "07069916947",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "10 9 02",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": "amakeobiwuru",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amake Habbeeb Mohammed",
    "email": "amakemohammed@aol.com",
    "username": "amakemohammed72",
    "phoneNumber": "07070016981",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "7 8 03",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": "jumokemohammed",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Wasiu Ngozi Edet",
    "email": "wasiuedet@outlook.com",
    "username": "wasiuedet9",
    "phoneNumber": "07070117015",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "7 7 08",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": "yemiedet",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Musa Ogechi George",
    "email": "musageorge@gmail.com",
    "username": "musageorge72",
    "phoneNumber": "08170217049",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "2 17 06",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": "esthergeorge",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Moses Emeka Obi",
    "email": "mosesobi@outlook.com",
    "username": "mosesobi23",
    "phoneNumber": "08170317083",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "1 10 02",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": "chinyereobi",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Victoria Teslim Doyle",
    "email": "victoriadoyle@aol.com",
    "username": "victoriadoyle27",
    "phoneNumber": "08170417117",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "12 1 02",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": "sophiadoyle",
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Samson Ahmed Onyebuchi",
    "email": "samsononyebuchi@hotmail.com",
    "username": "samsononyebuchi22",
    "phoneNumber": "07070517151",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "12 4 08",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": "mondayonyebuchi",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Samuel Chikaodili Lawnson",
    "email": "samuellawnson@aol.com",
    "username": "samuellawnson90",
    "phoneNumber": "08170617185",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "2 19 08",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": "yemilawnson",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Abuchi Emeka Akintunde",
    "email": "abuchiakintunde@gmail.com",
    "username": "abuchiakintunde86",
    "phoneNumber": "08170717219",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "5 9 04",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": "mariaakintunde",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Grace Esther Olanrewaju",
    "email": "graceolanrewaju@outlook.com",
    "username": "graceolanrewaju77",
    "phoneNumber": "07070817253",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "8 9 05",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": "anthonyolanrewaju",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Chikaodili Amara Omo-ojuile",
    "email": "chikaodiliomo-ojuile@outlook.com",
    "username": "chikaodiliomo-ojuile39",
    "phoneNumber": "07070917287",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "6 17 07",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": "abuchiomo-ojuile",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Eketi Tunde Nweke",
    "email": "eketinweke@aol.com",
    "username": "eketinweke55",
    "phoneNumber": "07071017321",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "12 26 05",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": "emekanweke",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Toyin Ibukun Idika",
    "email": "toyinidika@gmail.com",
    "username": "toyinidika61",
    "phoneNumber": "07071117355",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "6 9 03",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": "toyinidika",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Bunmi Gbemisola Bbatunde",
    "email": "bunmibbatunde@outlook.com",
    "username": "bunmibbatunde75",
    "phoneNumber": "07071217389",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "5 11 08",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": "jumokebbatunde",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Samson Toyin Ojerinde",
    "email": "samsonojerinde@aol.com",
    "username": "samsonojerinde46",
    "phoneNumber": "09071317423",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "6 12 06",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": "abubakarojerinde",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amanda Monday Adewole",
    "email": "amandaadewole@gmail.com",
    "username": "amandaadewole59",
    "phoneNumber": "07071417457",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "9 8 04",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": "aishaadewole",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Daniel Amake Ikokwu",
    "email": "danielikokwu@outlook.com",
    "username": "danielikokwu9",
    "phoneNumber": "07071517491",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "4 25 04",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": "mondayikokwu",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Monday Chikaodili Igwe",
    "email": "mondayigwe@aol.com",
    "username": "mondayigwe69",
    "phoneNumber": "07071617525",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "11 15 07",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": "sundayigwe",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Godswill Folake Savage",
    "email": "godswillsavage@gmail.com",
    "username": "godswillsavage64",
    "phoneNumber": "07071717559",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "6 2 07",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": "mariasavage",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Aisha Chioma Adewummi",
    "email": "aishaadewummi@aol.com",
    "username": "aishaadewummi26",
    "phoneNumber": "09071817593",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "7 21 02",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": "chinyereadewummi",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Constance Adewale Olamide",
    "email": "constanceolamide@gmail.com",
    "username": "constanceolamide68",
    "phoneNumber": "09071917627",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "2 9 05",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": "danielolamide",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Grace Chinyere Aworinde",
    "email": "graceaworinde@gmail.com",
    "username": "graceaworinde74",
    "phoneNumber": "09072017661",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "3 10 07",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": "gboyegaaworinde",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Daniel Ngozi Okoli",
    "email": "danielokoli@outlook.com",
    "username": "danielokoli64",
    "phoneNumber": "09072117695",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "12 26 04",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": "anthonyokoli",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Maria Maria Adekanbi",
    "email": "mariaadekanbi@aol.com",
    "username": "mariaadekanbi50",
    "phoneNumber": "08172217729",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "9 19 06",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": "godswilladekanbi",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Musa Moses Cole",
    "email": "musacole@outlook.com",
    "username": "musacole58",
    "phoneNumber": "08172317763",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "5 21 06",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": "danielcole",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Olasunkanmi Eketi Solarin",
    "email": "olasunkanmisolarin@outlook.com",
    "username": "olasunkanmisolarin70",
    "phoneNumber": "08172417797",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "7 9 08",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": "chikaodilisolarin",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Toyin Titilayo Mbanefo",
    "email": "toyinmbanefo@outlook.com",
    "username": "toyinmbanefo19",
    "phoneNumber": "09072517831",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "1 26 06",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": "lawrencembanefo",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Echezona Ebuka Olasupo",
    "email": "echezonaolasupo@outlook.com",
    "username": "echezonaolasupo57",
    "phoneNumber": "07072617865",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "5 18 06",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": "jumokeolasupo",
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Jumoke Chiamaka Tafawa",
    "email": "jumoketafawa@outlook.com",
    "username": "jumoketafawa13",
    "phoneNumber": "09072717899",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "4 10 04",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": "musatafawa",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Hannah Funsho Omotosho",
    "email": "hannahomotosho@outlook.com",
    "username": "hannahomotosho62",
    "phoneNumber": "07072817933",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "1 22 05",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": "echezonaomotosho",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Maria Amanda Nwafor",
    "email": "marianwafor@gmail.com",
    "username": "marianwafor3",
    "phoneNumber": "08172917967",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "1 14 05",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": "imaobongnwafor",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Joseph Lawrence Abraham",
    "email": "josephabraham@outlook.com",
    "username": "josephabraham1",
    "phoneNumber": "08173018001",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "9 27 04",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": "mosesabraham",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Chikaodili Samson Mmuoma",
    "email": "chikaodilimmuoma@hotmail.com",
    "username": "chikaodilimmuoma25",
    "phoneNumber": "09073118035",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "4 21 06",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": "ngozimmuoma",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Yemi Moses Awirigwe",
    "email": "yemiawirigwe@hotmail.com",
    "username": "yemiawirigwe36",
    "phoneNumber": "08173218069",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "12 10 05",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": "amaawirigwe",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Hannah Ama Abdul",
    "email": "hannahabdul@aol.com",
    "username": "hannahabdul86",
    "phoneNumber": "09073318103",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "4 24 03",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": "mosesabdul",
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Azeez Folake Azeez",
    "email": "azeezazeez@hotmail.com",
    "username": "azeezazeez65",
    "phoneNumber": "08173418137",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "3 1 07",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": "ebukaazeez",
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amanda Teslim Awolowo",
    "email": "amandaawolowo@outlook.com",
    "username": "amandaawolowo28",
    "phoneNumber": "09073518171",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "10 8 06",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": "johnawolowo",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Ebuka Lawrence Oputa",
    "email": "ebukaoputa@hotmail.com",
    "username": "ebukaoputa39",
    "phoneNumber": "09073618205",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "4 23 06",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": "amaraoputa",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Kevin Mary Effiong",
    "email": "kevineffiong@hotmail.com",
    "username": "kevineffiong24",
    "phoneNumber": "08173718239",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "2 17 04",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": "johneffiong",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amanda Victoria Ebisi",
    "email": "amandaebisi@outlook.com",
    "username": "amandaebisi13",
    "phoneNumber": "08173818273",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "12 24 07",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": "adewaleebisi",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amara Lawrence Babatunde",
    "email": "amarababatunde@aol.com",
    "username": "amarababatunde90",
    "phoneNumber": "08173918307",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "10 28 05",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": "chinyerebabatunde",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Lawrence Yemi Ayantola",
    "email": "lawrenceayantola@gmail.com",
    "username": "lawrenceayantola84",
    "phoneNumber": "09074018341",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "9 23 03",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": "wasiuayantola",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Rita Habbeeb Monday",
    "email": "ritamonday@hotmail.com",
    "username": "ritamonday63",
    "phoneNumber": "07074118375",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "6 14 07",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": "iniobongmonday",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Sophia Chikaodili Okeke",
    "email": "sophiaokeke@gmail.com",
    "username": "sophiaokeke90",
    "phoneNumber": "07074218409",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "3 13 03",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": "ibukunokeke",
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Kevin Samson Atanda",
    "email": "kevinatanda@outlook.com",
    "username": "kevinatanda8",
    "phoneNumber": "08174318443",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "5 1 03",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": "musaatanda",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Eketi Habbeeb Obiwuru",
    "email": "eketiobiwuru@gmail.com",
    "username": "eketiobiwuru83",
    "phoneNumber": "09074418477",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "1 16 07",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": "amakeobiwuru",
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Mary Maria Mohammed",
    "email": "marymohammed@hotmail.com",
    "username": "marymohammed15",
    "phoneNumber": "08174518511",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "9 11 06",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": "jumokemohammed",
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Constance Funsho Edet",
    "email": "constanceedet@hotmail.com",
    "username": "constanceedet79",
    "phoneNumber": "08174618545",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "9 4 06",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": "yemiedet",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Tunde Grace George",
    "email": "tundegeorge@aol.com",
    "username": "tundegeorge73",
    "phoneNumber": "09074718579",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "11 13 08",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": "esthergeorge",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amake Daniel Obi",
    "email": "amakeobi@outlook.com",
    "username": "amakeobi58",
    "phoneNumber": "08174818613",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "9 19 07",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": "chinyereobi",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Sarah Tunde Doyle",
    "email": "sarahdoyle@hotmail.com",
    "username": "sarahdoyle24",
    "phoneNumber": "09074918647",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "8 14 03",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": "sophiadoyle",
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Mary Amara Onyebuchi",
    "email": "maryonyebuchi@outlook.com",
    "username": "maryonyebuchi67",
    "phoneNumber": "08175018681",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "1 16 04",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": "mondayonyebuchi",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Moses John Lawnson",
    "email": "moseslawnson@hotmail.com",
    "username": "moseslawnson6",
    "phoneNumber": "08175118715",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "2 2 08",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": "yemilawnson",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Chiamaka Anthony Akintunde",
    "email": "chiamakaakintunde@outlook.com",
    "username": "chiamakaakintunde13",
    "phoneNumber": "08175218749",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "7 3 02",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": "mariaakintunde",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Yemi Chikaodili Olanrewaju",
    "email": "yemiolanrewaju@outlook.com",
    "username": "yemiolanrewaju34",
    "phoneNumber": "09075318783",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "5 10 05",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": "anthonyolanrewaju",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Toyin Chiamaka Omo-ojuile",
    "email": "toyinomo-ojuile@aol.com",
    "username": "toyinomo-ojuile30",
    "phoneNumber": "08175418817",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "3 22 08",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": "abuchiomo-ojuile",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Samson Lawrence Nweke",
    "email": "samsonnweke@aol.com",
    "username": "samsonnweke7",
    "phoneNumber": "08175518851",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "2 25 08",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": "emekanweke",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Sarah Temidayo Idika",
    "email": "sarahidika@aol.com",
    "username": "sarahidika22",
    "phoneNumber": "07075618885",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "6 14 02",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": "toyinidika",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Chinyere Funsho Bbatunde",
    "email": "chinyerebbatunde@hotmail.com",
    "username": "chinyerebbatunde54",
    "phoneNumber": "08175718919",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "5 14 08",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": "jumokebbatunde",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Chikaodili Matthew Ojerinde",
    "email": "chikaodiliojerinde@gmail.com",
    "username": "chikaodiliojerinde7",
    "phoneNumber": "07075818953",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "9 4 08",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": "abubakarojerinde",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amanda Ngozi Adewole",
    "email": "amandaadewole@outlook.com",
    "username": "amandaadewole19",
    "phoneNumber": "08175918987",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "4 10 04",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": "aishaadewole",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Yemi Ibukun Ikokwu",
    "email": "yemiikokwu@gmail.com",
    "username": "yemiikokwu71",
    "phoneNumber": "09076019021",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "7 4 03",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": "mondayikokwu",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Matthew Emeka Igwe",
    "email": "matthewigwe@aol.com",
    "username": "matthewigwe62",
    "phoneNumber": "09076119055",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "2 5 05",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": "sundayigwe",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Godswill Victoria Savage",
    "email": "godswillsavage@aol.com",
    "username": "godswillsavage80",
    "phoneNumber": "07076219089",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "12 11 06",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": "mariasavage",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Rita Imaobong Adewummi",
    "email": "ritaadewummi@gmail.com",
    "username": "ritaadewummi54",
    "phoneNumber": "09076319123",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "3 20 05",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": "chinyereadewummi",
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Funsho Umaru Olamide",
    "email": "funshoolamide@outlook.com",
    "username": "funshoolamide40",
    "phoneNumber": "08176419157",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "2 8 04",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": "danielolamide",
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Echezona Ogechi Aworinde",
    "email": "echezonaaworinde@gmail.com",
    "username": "echezonaaworinde63",
    "phoneNumber": "07076519191",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "1 14 05",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": "gboyegaaworinde",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Ebuka Adewale Okoli",
    "email": "ebukaokoli@gmail.com",
    "username": "ebukaokoli30",
    "phoneNumber": "09076619225",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "7 17 04",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": "anthonyokoli",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Ahmed Emeka Adekanbi",
    "email": "ahmedadekanbi@outlook.com",
    "username": "ahmedadekanbi5",
    "phoneNumber": "07076719259",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "12 20 07",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": "godswilladekanbi",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Anthony Obi Cole",
    "email": "anthonycole@gmail.com",
    "username": "anthonycole84",
    "phoneNumber": "07076819293",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "10 2 03",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": "danielcole",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Moses Moses Solarin",
    "email": "mosessolarin@gmail.com",
    "username": "mosessolarin12",
    "phoneNumber": "09076919327",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "1 19 08",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": "chikaodilisolarin",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Teslim Chioma Mbanefo",
    "email": "teslimmbanefo@outlook.com",
    "username": "teslimmbanefo90",
    "phoneNumber": "07077019361",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "1 21 03",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": "lawrencembanefo",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Victoria Toyin Olasupo",
    "email": "victoriaolasupo@gmail.com",
    "username": "victoriaolasupo52",
    "phoneNumber": "09077119395",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "10 4 07",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": "jumokeolasupo",
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Yemi Matthew Tafawa",
    "email": "yemitafawa@gmail.com",
    "username": "yemitafawa77",
    "phoneNumber": "08177219429",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "8 21 06",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": "musatafawa",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Olasunkanmi Abubakar Omotosho",
    "email": "olasunkanmiomotosho@gmail.com",
    "username": "olasunkanmiomotosho76",
    "phoneNumber": "09077319463",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "4 12 07",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": "echezonaomotosho",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Emeka Amanda Nwafor",
    "email": "emekanwafor@hotmail.com",
    "username": "emekanwafor36",
    "phoneNumber": "08177419497",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "2 2 03",
    "schoolAddress": "55 Obi Street New Housing Estate",
    "schoolName": "Kings College",
    "parentUsername": "imaobongnwafor",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amara Gboyega Abraham",
    "email": "amaraabraham@outlook.com",
    "username": "amaraabraham23",
    "phoneNumber": "08177519531",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "12 14 04",
    "schoolAddress": "55 Obi Street New Housing Estate",
    "schoolName": "Kings College",
    "parentUsername": "mosesabraham",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Chiamaka Samuel Mmuoma",
    "email": "chiamakammuoma@aol.com",
    "username": "chiamakammuoma69",
    "phoneNumber": "07077619565",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "12 7 05",
    "schoolAddress": "55 Obi Street New Housing Estate",
    "schoolName": "Kings College",
    "parentUsername": "ngozimmuoma",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Aisha Teslim Awirigwe",
    "email": "aishaawirigwe@gmail.com",
    "username": "aishaawirigwe9",
    "phoneNumber": "09077719599",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "10 15 06",
    "schoolAddress": "55 Obi Street New Housing Estate",
    "schoolName": "Kings College",
    "parentUsername": "amaawirigwe",
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Samson Temidayo Abdul",
    "email": "samsonabdul@gmail.com",
    "username": "samsonabdul85",
    "phoneNumber": "09077819633",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "2 19 07",
    "schoolAddress": "55 Obi Street New Housing Estate",
    "schoolName": "Kings College",
    "parentUsername": "mosesabdul",
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Folake Daniel Azeez",
    "email": "folakeazeez@gmail.com",
    "username": "folakeazeez88",
    "phoneNumber": "09077919667",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "5 16 07",
    "schoolAddress": "55 Obi Street New Housing Estate",
    "schoolName": "Kings College",
    "parentUsername": "ebukaazeez",
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Sarah Sarah Awolowo",
    "email": "sarahawolowo@aol.com",
    "username": "sarahawolowo42",
    "phoneNumber": "09078019701",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "2 23 03",
    "schoolAddress": "55 Obi Street New Housing Estate",
    "schoolName": "Kings College",
    "parentUsername": "johnawolowo",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Chioma Umaru Oputa",
    "email": "chiomaoputa@outlook.com",
    "username": "chiomaoputa70",
    "phoneNumber": "09078119735",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "7 26 03",
    "schoolAddress": "55 Obi Street New Housing Estate",
    "schoolName": "Kings College",
    "parentUsername": "amaraoputa",
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Musa Obi Effiong",
    "email": "musaeffiong@aol.com",
    "username": "musaeffiong86",
    "phoneNumber": "09078219769",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "4 16 06",
    "schoolAddress": "55 Obi Street New Housing Estate",
    "schoolName": "Kings College",
    "parentUsername": "johneffiong",
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Lawrence Emmanuel Ebisi",
    "email": "lawrenceebisi@gmail.com",
    "username": "lawrenceebisi40",
    "phoneNumber": "08178319803",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "10 10 05",
    "schoolAddress": "55 Obi Street New Housing Estate",
    "schoolName": "Kings College",
    "parentUsername": "adewaleebisi",
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  }
]
