[
  {
    "fullname": "Rita Samson Babatunde",
    "email": "RitaBbatunde@outlook.com",
    "username": "ritabbatunde",
    "phoneNumber": "09069416777",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Lawrence Iniobong Monday",
    "email": "LawrenceMonday@outlook.com",
    "username": "lawrencemonday",
    "phoneNumber": "09069516811",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Joseph Amara Ayantola",
    "email": "JosephAyantola@aol.com",
    "username": "josephayantola",
    "phoneNumber": "08169616845",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Victoria Titilayo Okeke",
    "email": "VictoriaOkeke@gmail.com",
    "username": "victoriaokeke",
    "phoneNumber": "08169716879",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Habbeeb Moses Ayantola",
    "email": "HabbeebAyantola@aol.com",
    "username": "habbeebayantola",
    "phoneNumber": "09069816913",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Abubakar Ibukun Atanda",
    "email": "AbubakarAtanda@gmail.com",
    "username": "abubakaratanda",
    "phoneNumber": "07069916947",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Anthony Joseph Bbatunde",
    "email": "AnthonyBbatunde@gmail.com",
    "username": "anthonybbatunde",
    "phoneNumber": "09070016981",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Sarah Ahmed Obiwuru",
    "email": "SarahObiwuru@aol.com",
    "username": "sarahobiwuru",
    "phoneNumber": "08170117015",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Onyeka Olasunkanmi Mohammed",
    "email": "OnyekaMohammed@gmail.com",
    "username": "onyekamohammed",
    "phoneNumber": "07070217049",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Fariat John Edet",
    "email": "FariatEdet@gmail.com",
    "username": "fariatedet",
    "phoneNumber": "08170317083",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "1057 Agege Road",
    "schoolName": "Marist Comprehensive",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Sophia Ngozi George",
    "email": "SophiaGeorge@gmail.com",
    "username": "sophiageorge",
    "phoneNumber": "07070417117",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": null,
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Rita John Obi",
    "email": "RitaObi@gmail.com",
    "username": "ritaobi",
    "phoneNumber": "08170517151",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Lawrence Funsho Doyle",
    "email": "LawrenceDoyle@gmail.com",
    "username": "lawrencedoyle",
    "phoneNumber": "08170617185",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Temidayo Grace Onyebuchi",
    "email": "TemidayoOnyebuchi@aol.com",
    "username": "temidayoonyebuchi",
    "phoneNumber": "09070717219",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Imaobong Fariat Okeke",
    "email": "ImaobongOkeke@hotmail.com",
    "username": "imaobongokeke",
    "phoneNumber": "07070817253",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Esther Ngozi Lawnson",
    "email": "EstherLawnson@outlook.com",
    "username": "estherlawnson",
    "phoneNumber": "07070917287",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Umaru Moses Akintunde",
    "email": "UmaruAkintunde@aol.com",
    "username": "umaruakintunde",
    "phoneNumber": "08171017321",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Chiamaka Joseph Olanrewaju",
    "email": "ChiamakaOlanrewaju@gmail.com",
    "username": "chiamakaolanrewaju",
    "phoneNumber": "07071117355",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Teslim Victoria Onyebuchi",
    "email": "TeslimOnyebuchi@hotmail.com",
    "username": "teslimonyebuchi",
    "phoneNumber": "08171217389",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Obi Toyin Olanrewaju",
    "email": "ObiOlanrewaju@outlook.com",
    "username": "obiolanrewaju",
    "phoneNumber": "09071317423",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "10 Olanrewaju Street",
    "schoolName": "Community High School Ojo",
    "parentUsername": null,
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Hannah Ama Omo-ojuile",
    "email": "HannahOmo-ojuile@gmail.com",
    "username": "hannahomo-ojuile",
    "phoneNumber": "08171417457",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Ogechi Abubakar Nweke",
    "email": "OgechiNweke@gmail.com",
    "username": "ogechinweke",
    "phoneNumber": "09071517491",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Godswill Constance Idika",
    "email": "GodswillIdika@gmail.com",
    "username": "godswillidika",
    "phoneNumber": "07071617525",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "John Hannah Bbatunde",
    "email": "JohnBbatunde@outlook.com",
    "username": "johnbbatunde",
    "phoneNumber": "07071717559",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Musa Yemi Ojerinde",
    "email": "MusaOjerinde@aol.com",
    "username": "musaojerinde",
    "phoneNumber": "09071817593",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Esther Abuchi Adewole",
    "email": "EstherAdewole@hotmail.com",
    "username": "estheradewole",
    "phoneNumber": "08171917627",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Emmanuel Chiamaka Ikokwu",
    "email": "EmmanuelIkokwu@aol.com",
    "username": "emmanuelikokwu",
    "phoneNumber": "08172017661",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Kevin Sophia Igwe",
    "email": "KevinIgwe@aol.com",
    "username": "kevinigwe",
    "phoneNumber": "08172117695",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Wasiu Bunmi Savage",
    "email": "WasiuSavage@outlook.com",
    "username": "wasiusavage",
    "phoneNumber": "08172217729",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Bukola Gbemisola Adewummi",
    "email": "BukolaAdewummi@outlook.com",
    "username": "bukolaadewummi",
    "phoneNumber": "08172317763",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "30 Ezekiel Street",
    "schoolName": "Hopebay College",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Yemi Imaobong Olamide",
    "email": "YemiOlamide@hotmail.com",
    "username": "yemiolamide",
    "phoneNumber": "07072417797",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Gboyega Jumoke Savage",
    "email": "GboyegaSavage@aol.com",
    "username": "gboyegasavage",
    "phoneNumber": "08172517831",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Sunday Esther Aworinde",
    "email": "SundayAworinde@gmail.com",
    "username": "sundayaworinde",
    "phoneNumber": "08172617865",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Lawrence Tayo Okoli",
    "email": "LawrenceOkoli@aol.com",
    "username": "lawrenceokoli",
    "phoneNumber": "09072717899",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "John Victoria Bbatunde",
    "email": "JohnBbatunde@hotmail.com",
    "username": "johnbbatunde",
    "phoneNumber": "09072817933",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Grace Atinuke Adekanbi",
    "email": "GraceAdekanbi@aol.com",
    "username": "graceadekanbi",
    "phoneNumber": "09072917967",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Chikaodili Gbemisola Cole",
    "email": "ChikaodiliCole@gmail.com",
    "username": "chikaodilicole",
    "phoneNumber": "09073018001",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Folake Daniel Ikokwu",
    "email": "FolakeIkokwu@gmail.com",
    "username": "folakeikokwu",
    "phoneNumber": "09073118035",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Hannah Sarah Solarin",
    "email": "HannahSolarin@hotmail.com",
    "username": "hannahsolarin",
    "phoneNumber": "08173218069",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Ahmed Gbemisola Bbatunde",
    "email": "AhmedBbatunde@gmail.com",
    "username": "ahmedbbatunde",
    "phoneNumber": "08173318103",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Balogun Street",
    "schoolName": "Atlantic Hall",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Adewale Temidayo Savage",
    "email": "AdewaleSavage@outlook.com",
    "username": "adewalesavage",
    "phoneNumber": "08173418137",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Maria Joseph Igwe",
    "email": "MariaIgwe@aol.com",
    "username": "mariaigwe",
    "phoneNumber": "09073518171",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "John Chioma Mbanefo",
    "email": "JohnMbanefo@outlook.com",
    "username": "johnmbanefo",
    "phoneNumber": "08173618205",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amara Onyeka Olasupo",
    "email": "AmaraOlasupo@outlook.com",
    "username": "amaraolasupo",
    "phoneNumber": "07073718239",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Monday Eketi Tafawa",
    "email": "MondayTafawa@aol.com",
    "username": "mondaytafawa",
    "phoneNumber": "07073818273",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Onyeka Constance Omotosho",
    "email": "OnyekaOmotosho@hotmail.com",
    "username": "onyekaomotosho",
    "phoneNumber": "09073918307",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Emmanuel Ama Nwafor",
    "email": "EmmanuelNwafor@outlook.com",
    "username": "emmanuelnwafor",
    "phoneNumber": "07074018341",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Atinuke Joseph Abraham",
    "email": "AtinukeAbraham@aol.com",
    "username": "atinukeabraham",
    "phoneNumber": "08174118375",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Abubakar Tunde Mmuoma",
    "email": "AbubakarMmuoma@aol.com",
    "username": "abubakarmmuoma",
    "phoneNumber": "09074218409",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Adewale Funsho Akintunde",
    "email": "AdewaleAkintunde@aol.com",
    "username": "adewaleakintunde",
    "phoneNumber": "09074318443",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Sunday Chinyere Okeke",
    "email": "SundayOkeke@aol.com",
    "username": "sundayokeke",
    "phoneNumber": "09074418477",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Mary Sarah Awirigwe",
    "email": "MaryAwirigwe@hotmail.com",
    "username": "maryawirigwe",
    "phoneNumber": "08174518511",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Monday Chioma Okonkwo",
    "email": "MondayOkonkwo@gmail.com",
    "username": "mondayokonkwo",
    "phoneNumber": "08174618545",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amanda Olasunkanmi Olaniyi",
    "email": "AmandaOlaniyi@gmail.com",
    "username": "amandaolaniyi",
    "phoneNumber": "07074718579",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Funsho Anthony Akintunde",
    "email": "FunshoAkintunde@gmail.com",
    "username": "funshoakintunde",
    "phoneNumber": "09074818613",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amara Abubakar Akintunde",
    "email": "AmaraAkintunde@outlook.com",
    "username": "amaraakintunde",
    "phoneNumber": "08174918647",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Sunday Sarah Mmaduka",
    "email": "SundayMmaduka@gmail.com",
    "username": "sundaymmaduka",
    "phoneNumber": "07075018681",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amara Teslim Nweke",
    "email": "AmaraNweke@hotmail.com",
    "username": "amaranweke",
    "phoneNumber": "09075118715",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Constance Teslim Abdul",
    "email": "ConstanceAbdul@outlook.com",
    "username": "constanceabdul",
    "phoneNumber": "07075218749",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Ngozi Gboyega Monday",
    "email": "NgoziMonday@outlook.com",
    "username": "ngozimonday",
    "phoneNumber": "07075318783",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Falomo Road",
    "schoolName": "Meadow Academy",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Daniel Moses Ikokwu",
    "email": "DanielIkokwu@aol.com",
    "username": "danielikokwu",
    "phoneNumber": "09075418817",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Teslim Samson Obiwuru",
    "email": "TeslimObiwuru@aol.com",
    "username": "teslimobiwuru",
    "phoneNumber": "09075518851",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Emmanuel Lawrence Olanrewaju",
    "email": "EmmanuelOlanrewaju@hotmail.com",
    "username": "emmanuelolanrewaju",
    "phoneNumber": "08175618885",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Emmanuel Joseph Nweke",
    "email": "EmmanuelNweke@hotmail.com",
    "username": "emmanuelnweke",
    "phoneNumber": "09075718919",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Bukola Amanda Azeez",
    "email": "BukolaAzeez@gmail.com",
    "username": "bukolaazeez",
    "phoneNumber": "07075818953",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": null,
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Musa Victoria Olamide",
    "email": "MusaOlamide@outlook.com",
    "username": "musaolamide",
    "phoneNumber": "09075918987",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": null,
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Amara Amake Tafawa",
    "email": "AmaraTafawa@aol.com",
    "username": "amaratafawa",
    "phoneNumber": "08176019021",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Jumoke Bbatunde Omotosho",
    "email": "JumokeOmotosho@outlook.com",
    "username": "jumokeomotosho",
    "phoneNumber": "07076119055",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Sunday Gboyega Awolowo",
    "email": "SundayAwolowo@aol.com",
    "username": "sundayawolowo",
    "phoneNumber": "09076219089",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Godswill Chiamaka Edet",
    "email": "GodswillEdet@aol.com",
    "username": "godswilledet",
    "phoneNumber": "08176319123",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "7 Cole Street Off Ajegunle Bus-Stop ",
    "schoolName": "Higher Achievers",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Imaobong Joseph Mmuoma",
    "email": "ImaobongMmuoma@outlook.com",
    "username": "imaobongmmuoma",
    "phoneNumber": "09076419157",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Habbeeb Moses George",
    "email": "HabbeebGeorge@outlook.com",
    "username": "habbeebgeorge",
    "phoneNumber": "08176519191",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Sunday Kevin Monday",
    "email": "SundayMonday@gmail.com",
    "username": "sundaymonday",
    "phoneNumber": "08176619225",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Toyin Aisha Ayantola",
    "email": "ToyinAyantola@hotmail.com",
    "username": "toyinayantola",
    "phoneNumber": "09076719259",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Rita Matthew Omotosho",
    "email": "RitaOmotosho@gmail.com",
    "username": "ritaomotosho",
    "phoneNumber": "09076819293",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": null,
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Grace Sunday Oputa",
    "email": "GraceOputa@outlook.com",
    "username": "graceoputa",
    "phoneNumber": "08176919327",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Folake Tayo Savage",
    "email": "FolakeSavage@gmail.com",
    "username": "folakesavage",
    "phoneNumber": "07077019361",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Moses Ama Cole",
    "email": "MosesCole@aol.com",
    "username": "mosescole",
    "phoneNumber": "07077119395",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": null,
    "class": "Basic 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Echezona Sarah Effiong",
    "email": "EchezonaEffiong@outlook.com",
    "username": "echezonaeffiong",
    "phoneNumber": "08177219429",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Bunmi Hannah Solarin",
    "email": "BunmiSolarin@hotmail.com",
    "username": "bunmisolarin",
    "phoneNumber": "07077319463",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "6 Morenikeji Street",
    "schoolName": "Crescent College",
    "parentUsername": null,
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Daniel Ogechi Omo-ojuile",
    "email": "DanielOmo-ojuile@outlook.com",
    "username": "danielomo-ojuile",
    "phoneNumber": "09077419497",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Jumoke John Obi",
    "email": "JumokeObi@hotmail.com",
    "username": "jumokeobi",
    "phoneNumber": "09077519531",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Umaru Yemi Atanda",
    "email": "UmaruAtanda@hotmail.com",
    "username": "umaruatanda",
    "phoneNumber": "07077619565",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Funsho Sunday Idika",
    "email": "FunshoIdika@outlook.com",
    "username": "funshoidika",
    "phoneNumber": "07077719599",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": null,
    "class": "Basic 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Hannah Atinuke Obi",
    "email": "HannahObi@hotmail.com",
    "username": "hannahobi",
    "phoneNumber": "08177819633",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": null,
    "class": "Basic 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Toyin Ogechi Ikokwu",
    "email": "ToyinIkokwu@hotmail.com",
    "username": "toyinikokwu",
    "phoneNumber": "09077919667",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Monday Moses Ebisi",
    "email": "MondayEbisi@gmail.com",
    "username": "mondayebisi",
    "phoneNumber": "09078019701",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Bukola Amara Idika",
    "email": "BukolaIdika@aol.com",
    "username": "bukolaidika",
    "phoneNumber": "08178119735",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": null,
    "class": "SS 1",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Ngozi Onyeka Akinyemi",
    "email": "NgoziAkinyemi@hotmail.com",
    "username": "ngoziakinyemi",
    "phoneNumber": "08178219769",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": null,
    "class": "SS 3",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  },
  {
    "fullname": "Victoria Godswill Solarin",
    "email": "VictoriaSolarin@outlook.com",
    "username": "victoriasolarin",
    "phoneNumber": "07078319803",
    "role": "Student",
    "category": "Student",
    "dateOfBirth": "\"Fri May 22 2020 18:27:09 GMT+0100 (West Africa Standard Time)\"",
    "schoolAddress": "55 Lamido Street Ahmed Musa GRA",
    "schoolName": "Notre Girls College",
    "parentUsername": null,
    "class": "SS 2",
    "activeStudent": true,
    "password": "qwerty12345",
    "confirmPassword": "qwerty12345"
  }
]
