[
    {
      "fullname": "Bbatunde Atinuke Babatunde",
      "email": "BbatundeBabatunde@aol.com",
      "username": "bbatundebabatunde",
      "phoneNumber": "08169416777",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Obi Teslim Ayantola",
      "email": "ObiAyantola@aol.com",
      "username": "obiayantola",
      "phoneNumber": "09069516811",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Juliet Tayo Monday",
      "email": "JulietMonday@outlook.com",
      "username": "julietmonday",
      "phoneNumber": "07069616845",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Bunmi Jumoke Okeke",
      "email": "BunmiOkeke@hotmail.com",
      "username": "bunmiokeke",
      "phoneNumber": "08169716879",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Musa Juliet Atanda",
      "email": "MusaAtanda@gmail.com",
      "username": "musaatanda",
      "phoneNumber": "07069816913",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Adewale Gboyega Obiwuru",
      "email": "AdewaleObiwuru@gmail.com",
      "username": "adewaleobiwuru",
      "phoneNumber": "09069916947",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Folake Funsho Mohammed",
      "email": "FolakeMohammed@hotmail.com",
      "username": "folakemohammed",
      "phoneNumber": "08170016981",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Onyeka Moses Edet",
      "email": "OnyekaEdet@outlook.com",
      "username": "onyekaedet",
      "phoneNumber": "09070117015",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Chioma Ogechi George",
      "email": "ChiomaGeorge@outlook.com",
      "username": "chiomageorge",
      "phoneNumber": "09070217049",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Anthony Eketi Obi",
      "email": "AnthonyObi@aol.com",
      "username": "anthonyobi",
      "phoneNumber": "08170317083",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Ahmed Samson Doyle",
      "email": "AhmedDoyle@gmail.com",
      "username": "ahmeddoyle",
      "phoneNumber": "09070417117",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Jumoke Atinuke Onyebuchi",
      "email": "JumokeOnyebuchi@hotmail.com",
      "username": "jumokeonyebuchi",
      "phoneNumber": "08170517151",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Joseph Moses Lawnson",
      "email": "JosephLawnson@outlook.com",
      "username": "josephlawnson",
      "phoneNumber": "09070617185",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Chinyere Echezona Akintunde",
      "email": "ChinyereAkintunde@hotmail.com",
      "username": "chinyereakintunde",
      "phoneNumber": "07070717219",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Amara Emmanuel Olanrewaju",
      "email": "AmaraOlanrewaju@hotmail.com",
      "username": "amaraolanrewaju",
      "phoneNumber": "09070817253",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Tunde John Omo-ojuile",
      "email": "TundeOmo-ojuile@aol.com",
      "username": "tundeomo-ojuile",
      "phoneNumber": "09070917287",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Chioma Matthew Nweke",
      "email": "ChiomaNweke@aol.com",
      "username": "chiomanweke",
      "phoneNumber": "08171017321",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Adewale Maria Idika",
      "email": "AdewaleIdika@gmail.com",
      "username": "adewaleidika",
      "phoneNumber": "07071117355",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Azeez Imaobong Bbatunde",
      "email": "AzeezBbatunde@gmail.com",
      "username": "azeezbbatunde",
      "phoneNumber": "08171217389",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Sophia Moses Ojerinde",
      "email": "SophiaOjerinde@gmail.com",
      "username": "sophiaojerinde",
      "phoneNumber": "09071317423",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Wasiu Folake Adewole",
      "email": "WasiuAdewole@gmail.com",
      "username": "wasiuadewole",
      "phoneNumber": "09071417457",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Gbemisola Abuchi Ikokwu",
      "email": "GbemisolaIkokwu@hotmail.com",
      "username": "gbemisolaikokwu",
      "phoneNumber": "07071517491",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Abuchi Funsho Igwe",
      "email": "AbuchiIgwe@outlook.com",
      "username": "abuchiigwe",
      "phoneNumber": "08171617525",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Ahmed Matthew Savage",
      "email": "AhmedSavage@hotmail.com",
      "username": "ahmedsavage",
      "phoneNumber": "07071717559",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Moses Chinyere Adewummi",
      "email": "MosesAdewummi@gmail.com",
      "username": "mosesadewummi",
      "phoneNumber": "09071817593",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Chioma Chinyere Olamide",
      "email": "ChiomaOlamide@hotmail.com",
      "username": "chiomaolamide",
      "phoneNumber": "07071917627",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Amanda Sophia Aworinde",
      "email": "AmandaAworinde@hotmail.com",
      "username": "amandaaworinde",
      "phoneNumber": "09072017661",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Mary Jumoke Okoli",
      "email": "MaryOkoli@hotmail.com",
      "username": "maryokoli",
      "phoneNumber": "09072117695",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Mary Monday Adekanbi",
      "email": "MaryAdekanbi@hotmail.com",
      "username": "maryadekanbi",
      "phoneNumber": "08172217729",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Anthony Obi Cole",
      "email": "AnthonyCole@hotmail.com",
      "username": "anthonycole",
      "phoneNumber": "09072317763",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Maria John Solarin",
      "email": "MariaSolarin@outlook.com",
      "username": "mariasolarin",
      "phoneNumber": "09072417797",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Amara Azeez Mbanefo",
      "email": "AmaraMbanefo@aol.com",
      "username": "amarambanefo",
      "phoneNumber": "08172517831",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Ibukun Yemi Olasupo",
      "email": "IbukunOlasupo@outlook.com",
      "username": "ibukunolasupo",
      "phoneNumber": "08172617865",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Fariat Iniobong Tafawa",
      "email": "FariatTafawa@outlook.com",
      "username": "fariattafawa",
      "phoneNumber": "07072717899",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Fariat Mary Omotosho",
      "email": "FariatOmotosho@outlook.com",
      "username": "fariatomotosho",
      "phoneNumber": "09072817933",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Titilayo John Nwafor",
      "email": "TitilayoNwafor@gmail.com",
      "username": "titilayonwafor",
      "phoneNumber": "07072917967",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Adewale Tunde Abraham",
      "email": "AdewaleAbraham@outlook.com",
      "username": "adewaleabraham",
      "phoneNumber": "09073018001",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Emeka Moses Mmuoma",
      "email": "EmekaMmuoma@aol.com",
      "username": "emekammuoma",
      "phoneNumber": "08173118035",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Constance Esther Awirigwe",
      "email": "ConstanceAwirigwe@hotmail.com",
      "username": "constanceawirigwe",
      "phoneNumber": "07073218069",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Teslim Wasiu Abdul",
      "email": "TeslimAbdul@gmail.com",
      "username": "teslimabdul",
      "phoneNumber": "09073318103",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Anthony Bbatunde Azeez",
      "email": "AnthonyAzeez@outlook.com",
      "username": "anthonyazeez",
      "phoneNumber": "08173418137",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Abubakar Matthew Awolowo",
      "email": "AbubakarAwolowo@aol.com",
      "username": "abubakarawolowo",
      "phoneNumber": "09073518171",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Samuel Victoria Oputa",
      "email": "SamuelOputa@aol.com",
      "username": "samueloputa",
      "phoneNumber": "08173618205",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Juliet Folake Effiong",
      "email": "JulietEffiong@outlook.com",
      "username": "julieteffiong",
      "phoneNumber": "07073718239",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Ogechi Jumoke Ebisi",
      "email": "OgechiEbisi@aol.com",
      "username": "ogechiebisi",
      "phoneNumber": "08173818273",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    }
  ]
  