[
    {
      "fullname": "Chinyere Teslim Babatunde",
      "email": "ChinyereBabatunde@gmail.com",
      "username": "chinyerebabatunde",
      "phoneNumber": "07069416777",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Wasiu Aisha Ayantola",
      "email": "WasiuAyantola@aol.com",
      "username": "wasiuayantola",
      "phoneNumber": "09069516811",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Iniobong Umaru Monday",
      "email": "IniobongMonday@hotmail.com",
      "username": "iniobongmonday",
      "phoneNumber": "08169616845",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Ibukun Eketi Okeke",
      "email": "IbukunOkeke@hotmail.com",
      "username": "ibukunokeke",
      "phoneNumber": "07069716879",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Musa Grace Atanda",
      "email": "MusaAtanda@aol.com",
      "username": "musaatanda",
      "phoneNumber": "09069816913",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Amake Aisha Obiwuru",
      "email": "AmakeObiwuru@hotmail.com",
      "username": "amakeobiwuru",
      "phoneNumber": "08169916947",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Jumoke Kevin Mohammed",
      "email": "JumokeMohammed@aol.com",
      "username": "jumokemohammed",
      "phoneNumber": "07070016981",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Yemi Echezona Edet",
      "email": "YemiEdet@aol.com",
      "username": "yemiedet",
      "phoneNumber": "07070117015",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Esther Teslim George",
      "email": "EstherGeorge@aol.com",
      "username": "esthergeorge",
      "phoneNumber": "08170217049",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Chinyere Toyin Obi",
      "email": "ChinyereObi@aol.com",
      "username": "chinyereobi",
      "phoneNumber": "08170317083",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Sophia Onyeka Doyle",
      "email": "SophiaDoyle@aol.com",
      "username": "sophiadoyle",
      "phoneNumber": "09070417117",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Monday Bukola Onyebuchi",
      "email": "MondayOnyebuchi@gmail.com",
      "username": "mondayonyebuchi",
      "phoneNumber": "08170517151",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Yemi Juliet Lawnson",
      "email": "YemiLawnson@outlook.com",
      "username": "yemilawnson",
      "phoneNumber": "07070617185",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Maria Iniobong Akintunde",
      "email": "MariaAkintunde@hotmail.com",
      "username": "mariaakintunde",
      "phoneNumber": "08170717219",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Anthony Ngozi Olanrewaju",
      "email": "AnthonyOlanrewaju@gmail.com",
      "username": "anthonyolanrewaju",
      "phoneNumber": "07070817253",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Abuchi Titilayo Omo-ojuile",
      "email": "AbuchiOmo-ojuile@gmail.com",
      "username": "abuchiomo-ojuile",
      "phoneNumber": "07070917287",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Emeka Godswill Nweke",
      "email": "EmekaNweke@aol.com",
      "username": "emekanweke",
      "phoneNumber": "09071017321",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Toyin Abuchi Idika",
      "email": "ToyinIdika@outlook.com",
      "username": "toyinidika",
      "phoneNumber": "07071117355",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Jumoke Juliet Bbatunde",
      "email": "JumokeBbatunde@hotmail.com",
      "username": "jumokebbatunde",
      "phoneNumber": "09071217389",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Abubakar Joseph Ojerinde",
      "email": "AbubakarOjerinde@aol.com",
      "username": "abubakarojerinde",
      "phoneNumber": "07071317423",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Aisha Matthew Adewole",
      "email": "AishaAdewole@outlook.com",
      "username": "aishaadewole",
      "phoneNumber": "07071417457",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Monday Amanda Ikokwu",
      "email": "MondayIkokwu@hotmail.com",
      "username": "mondayikokwu",
      "phoneNumber": "09071517491",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Sunday Kevin Igwe",
      "email": "SundayIgwe@gmail.com",
      "username": "sundayigwe",
      "phoneNumber": "09071617525",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Maria Abuchi Savage",
      "email": "MariaSavage@outlook.com",
      "username": "mariasavage",
      "phoneNumber": "08171717559",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Chinyere Godswill Adewummi",
      "email": "ChinyereAdewummi@hotmail.com",
      "username": "chinyereadewummi",
      "phoneNumber": "07071817593",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Daniel Ogechi Olamide",
      "email": "DanielOlamide@outlook.com",
      "username": "danielolamide",
      "phoneNumber": "08171917627",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Gboyega Habbeeb Aworinde",
      "email": "GboyegaAworinde@gmail.com",
      "username": "gboyegaaworinde",
      "phoneNumber": "08172017661",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Anthony Adewale Okoli",
      "email": "AnthonyOkoli@outlook.com",
      "username": "anthonyokoli",
      "phoneNumber": "09072117695",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Godswill Iniobong Adekanbi",
      "email": "GodswillAdekanbi@hotmail.com",
      "username": "godswilladekanbi",
      "phoneNumber": "08172217729",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Daniel Obi Cole",
      "email": "DanielCole@aol.com",
      "username": "danielcole",
      "phoneNumber": "07072317763",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Chikaodili Bbatunde Solarin",
      "email": "ChikaodiliSolarin@outlook.com",
      "username": "chikaodilisolarin",
      "phoneNumber": "08172417797",
      "role": "Guardian",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Lawrence Constance Mbanefo",
      "email": "LawrenceMbanefo@hotmail.com",
      "username": "lawrencembanefo",
      "phoneNumber": "07072517831",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Jumoke Teslim Olasupo",
      "email": "JumokeOlasupo@gmail.com",
      "username": "jumokeolasupo",
      "phoneNumber": "07072617865",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Musa Ebuka Tafawa",
      "email": "MusaTafawa@hotmail.com",
      "username": "musatafawa",
      "phoneNumber": "07072717899",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Echezona Onyeka Omotosho",
      "email": "EchezonaOmotosho@outlook.com",
      "username": "echezonaomotosho",
      "phoneNumber": "07072817933",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Imaobong Teslim Nwafor",
      "email": "ImaobongNwafor@aol.com",
      "username": "imaobongnwafor",
      "phoneNumber": "08172917967",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Moses Gbemisola Abraham",
      "email": "MosesAbraham@gmail.com",
      "username": "mosesabraham",
      "phoneNumber": "09073018001",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Ngozi Tunde Mmuoma",
      "email": "NgoziMmuoma@aol.com",
      "username": "ngozimmuoma",
      "phoneNumber": "09073118035",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Ama Juliet Awirigwe",
      "email": "AmaAwirigwe@outlook.com",
      "username": "amaawirigwe",
      "phoneNumber": "07073218069",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Moses Ogechi Abdul",
      "email": "MosesAbdul@hotmail.com",
      "username": "mosesabdul",
      "phoneNumber": "07073318103",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Ebuka Moses Azeez",
      "email": "EbukaAzeez@outlook.com",
      "username": "ebukaazeez",
      "phoneNumber": "08173418137",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "John Folake Awolowo",
      "email": "JohnAwolowo@aol.com",
      "username": "johnawolowo",
      "phoneNumber": "09073518171",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Amara Wasiu Oputa",
      "email": "AmaraOputa@outlook.com",
      "username": "amaraoputa",
      "phoneNumber": "07073618205",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "John Daniel Effiong",
      "email": "JohnEffiong@hotmail.com",
      "username": "johneffiong",
      "phoneNumber": "09073718239",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    },
    {
      "fullname": "Adewale John Ebisi",
      "email": "AdewaleEbisi@gmail.com",
      "username": "adewaleebisi",
      "phoneNumber": "09073818273",
      "role": "Parent",
      "category": "Parent",
      "active": true,
      "password": "qwerty12345",
      "confirmPassword": "qwerty12345"
    }
  ]
  